name: Build and Deploy with Docker to EC2

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Added permissions block
      packages: write # Grant write permission to GHCR packages
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            VERSION=${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH connection
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa # Important: Remove CR
          chmod 400 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts # Use the stored known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "Testing SSH connection..."
          ssh -v -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }}  #Added port

      - name: Deploy to EC2
        run: |
          echo "Connecting to EC2 instance..."
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} << EOF
            set -x # Debug: Print commands
            echo "Logged in to EC2"
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop hello-world-container || true
            docker rm hello-world-container || true
            docker run -d -p 80:8000 --name hello-world-container ghcr.io/${{ github.repository }}:latest
            echo "Deployment successful!"
          EOF
